- name: Nginx | Install the init script
  template:
    src: nginx.service.j2
    dest: /etc/systemd/system/nginx.service
    owner: root
    group: root
    mode: 0755
  notify:
    - restart nginx


